// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualDLS
{
    static class Vsix
    {
        public const string Id = "VisualDLS.96c8f1fa-8361-4871-9d5f-5fb43eaddf19";
        public const string Name = "Dlang";
        public const string Description = @"D language support for Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Laurent Tréguier";
        public const string Tags = "d dlang lsp language-server";
    }
}
